---
services:
  transformers-notebook:
    build: ./
    #image: jupyter/tensorflow-notebook
    ports:
      - 8000:8888
    environment:
      - JUPYTER_TOKEN=iambatman
    volumes:
      - ./:/home/jovyan